FROM phusion/baseimage:0.9.17
MAINTAINER pitrho

ENV DEBIAN_FRONTEND noninteractive
ENV CASSANDRA_VERSION %%CASSANDRA_VERSION%%

# Install Oracle Java 8
RUN apt-add-repository ppa:webupd8team/java \
  && apt-get update \
  && echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections \
  && apt-get install -y oracle-java8-installer dnsutils python python-support

RUN curl -L -O http://dl.bintray.com/apache/cassandra/pool/main/c/cassandra/cassandra_%%CASSANDRA_VERSION%%_all.deb \
  && dpkg -i cassandra_%%CASSANDRA_VERSION%%_all.deb \
  && update-rc.d -f cassandra remove \
  && rm cassandra_%%CASSANDRA_VERSION%%_all.deb

RUN curl -L -O http://dl.bintray.com/apache/cassandra/pool/main/c/cassandra/cassandra-tools_%%CASSANDRA_VERSION%%_all.deb \
  && dpkg -i cassandra-tools_%%CASSANDRA_VERSION%%_all.deb \
  && update-rc.d -f cassandra remove \
  && rm cassandra-tools_%%CASSANDRA_VERSION%%_all.deb

RUN apt-get update && apt-get install -y -q expect-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ENV CASSANDRA_CONFIG /etc/cassandra

# Add all services files
RUN mkdir /root/.cassandra /etc/service/nodetool
COPY run.sh /etc/service/nodetool/run
COPY run-nodetool.sh /etc/service/nodetool/run-nodetool.sh

CMD ["/sbin/my_init"]
